// Package httpapi exposes the REST API. Public routes serve the customer and
// merchant apps; /v1/admin routes need a signed-in admin and check their role.
package httpapi

import (
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/jackc/pgx/v5/pgxpool"

	"logaluxe/api/internal/config"
	"logaluxe/api/internal/mail"
	"logaluxe/api/internal/storage"
)

type Server struct {
	cfg            config.Config
	pool           database
	paymentEffects *[]func()
	paymentFailure error
	store          *storage.S3 // nil when image storage is not configured
	mail           *mail.Mailer
	limits         *limiter
}

func New(cfg config.Config, pool *pgxpool.Pool) http.Handler {
	s := &Server{cfg: cfg, pool: pool, store: storage.New(cfg.AWSRegion, cfg.AWSBucket, cfg.AWSAccessKey, cfg.AWSSecretKey),
		mail: mail.New(mail.Config{Provider: cfg.MailProvider, From: cfg.MailFrom, ResendKey: cfg.ResendKey, RelyKitKey: cfg.RelyKitKey, RelyKitURL: cfg.RelyKitURL,
			SMTPHost: cfg.SMTPHost, SMTPPort: cfg.SMTPPort, SMTPUser: cfg.SMTPUser, SMTPPass: cfg.SMTPPass, SMTPSecure: cfg.SMTPSecure})}
	s.limits = newLimiter()
	r := chi.NewRouter()
	r.Use(middleware.RequestID, middleware.RealIP, middleware.Recoverer)
	r.Use(middleware.Timeout(60 * time.Second))
	r.Use(s.cors)
	r.Use(logRequests)

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		if err := pool.Ping(r.Context()); err != nil {
			writeErr(w, http.StatusServiceUnavailable, "database unreachable")
			return
		}
		writeJSON(w, 200, M{"ok": true, "env": cfg.Env, "payments": cfg.PaymentsMode()})
	})

	r.Route("/v1", func(r chi.Router) {
		r.Get("/app-return/{screen}", s.appReturn)
		r.Get("/features", s.features)
		r.With(s.limit("code-send", 6, 10*time.Minute)).Post("/auth/code/send", s.authCodeSend)
		r.With(s.limit("code-verify", 30, 10*time.Minute)).Post("/auth/code/verify", s.authCodeVerify)
		r.Get("/businesses", s.listBusinesses)
		r.Get("/locate", s.locate)
		r.Get("/places", s.listPlaces)
		r.Get("/places/search", s.searchPlaces)
		r.Get("/places/reverse", s.reversePlace)
		r.Get("/places/states", s.listStates)
		r.With(s.limit("locate", 40, 10*time.Minute)).Post("/places/locate", s.locatePlace)
		r.Get("/places/{slug}", s.getPlace)
		r.Get("/businesses/{slug}", s.getBusiness)
		r.Get("/businesses/{slug}/availability", s.availability)
		r.Get("/businesses/{slug}/openings", s.openings)
		r.Get("/businesses/{slug}/days", s.openDays)
		r.Get("/businesses/{slug}/reviews", s.businessReviews)
		r.Get("/openings", s.openingsBatch)
		r.Get("/bookings/{id}/calendar.ics", s.bookingCalendar)
		r.Get("/cal/{token}", s.calFeed)
		r.With(s.limit("book", 30, time.Hour)).Post("/bookings", s.createBooking)
		r.Get("/bookings/{id}", s.getBooking)
		r.With(s.limit("waitlist", 20, time.Hour)).Post("/waitlist", s.joinWaitlist)

		r.Get("/products", s.listProducts)
		r.Get("/products/{slug}", s.getProduct)
		r.Get("/products-extras", s.productsExtras)
		r.With(s.limit("order", 30, time.Hour)).Post("/orders", s.createOrder)
		r.With(s.limit("quote", 600, time.Hour)).Post("/orders/quote", s.createOrder)
		r.Get("/gift-cards/options", s.giftOptions)
		r.With(s.limit("gift", 20, time.Hour)).Post("/gift-cards/buy", s.giftBuy)
		r.Get("/orders/{id}", s.getOrder)

		r.Get("/site/media", s.siteMedia)
		r.Get("/media/{id}", s.mediaFile)

		r.With(s.limit("codes", 40, 10*time.Minute)).Post("/checkout/check", s.checkoutCheck)

		// Customer accounts.
		r.With(s.limit("handoff", 30, 10*time.Minute)).Post("/auth/web-handoff/preview", s.webHandoffPreview)
		r.With(s.limit("handoff", 30, 10*time.Minute)).Post("/auth/web-handoff/exchange", s.webHandoffExchange)
		r.With(s.limit("signup", 10, time.Hour)).Post("/auth/signup", s.authSignup)
		r.With(s.limit("login", 20, 10*time.Minute)).Post("/auth/login", s.authLogin)
		r.Post("/auth/logout", s.authLogout)
		r.With(s.limit("forgot", 6, time.Hour)).Post("/auth/forgot", s.authForgot)
		r.With(s.limit("reset", 20, time.Hour)).Post("/auth/reset", s.authReset)
		r.With(s.limit("verify", 30, 10*time.Minute)).Post("/auth/verify", s.authVerify)
		r.Group(func(r chi.Router) {
			r.Use(s.requireCustomer)
			r.Post("/auth/push", s.authPush)
			r.Get("/auth/push", s.authPush)
			r.Delete("/auth/push", s.authPush)
			r.Get("/auth/me", s.authMe)
			r.With(s.limit("handoff-create", 20, 10*time.Minute)).Post("/auth/web-handoff", s.authWebHandoff)
			r.Put("/auth/me", s.authUpdate)
			r.Get("/auth/sessions", s.authSessions)
			r.Delete("/auth/sessions/{id}", s.authSessionRevoke)
			r.With(s.limit("account-export", 6, time.Hour)).Get("/auth/export", s.authExport)
			r.With(s.limit("account-delete", 5, time.Hour)).Post("/auth/delete", s.authDelete)
			r.Post("/auth/password", s.authPassword)
			r.Post("/auth/verify/send", s.authVerifySend)
			r.Post("/auth/bookings/{id}/cancel", s.authCancelBooking)
			r.Post("/auth/bookings/{id}/review", s.authReview)
			r.Get("/auth/threads", s.authThreads)
			r.Get("/auth/cards", s.authCards)
			r.Delete("/auth/cards/{id}", s.authCardDelete)
			r.With(s.limit("code-send", 6, 10*time.Minute)).Post("/auth/phone/send", s.authPhoneSend)
			r.Post("/auth/phone/verify", s.authPhoneVerify)
			r.Put("/auth/channel", s.authChannel)
			r.Get("/auth/bookings/{id}", s.authBooking)
			r.Post("/auth/bookings/{id}/reschedule", s.authReschedule)
			r.Get("/auth/favourites", s.authFavourites)
			r.Put("/auth/favourites/{slug}", s.authFavouriteSet)
			r.Delete("/auth/favourites/{slug}", s.authFavouriteSet)
			r.Get("/auth/wallet", s.authWallet)
			r.Post("/auth/products/{slug}/review", s.authProductReview)
			r.Post("/auth/orders/{id}/cancel", s.authOrderCancel)
			r.Get("/auth/favourite-products", s.authFavProducts)
			r.Put("/auth/favourite-products/{slug}", s.authFavProductSet)
			r.Delete("/auth/favourite-products/{slug}", s.authFavProductSet)
			r.Post("/auth/reviews/{id}/photos", s.authReviewPhoto)
			r.Delete("/auth/review-photos/{id}", s.authReviewPhotoDelete)
			r.Get("/auth/referral", s.authReferral)
			r.Post("/auth/orders/{id}/returns", s.authReturnAsk)
			r.Post("/auth/bookings/{id}/problem", s.authBookingProblem)
			r.Post("/auth/bookings/{id}/tip", s.authBookingTip)
			r.Post("/auth/bookings/{id}/repeat", s.authBookingRepeat)
			r.Post("/auth/threads", s.authThreadSend)
			r.Get("/auth/threads/{id}", s.authThread)
		})
		r.With(s.limit("support", 10, time.Hour)).Post("/support", s.supportCreate)
		r.Get("/pages/{slug}", s.sitePage)

		// The Journal: articles about beauty. Public reads see only what is live.
		r.Get("/journal", s.journalList)
		r.Get("/journal/home", s.journalHome)
		r.Get("/journal/{slug}", s.journalRead)
		r.Get("/journal/{slug}/professionals", s.journalProfessionals)

		// The merchant web: people who run a business.
		// Payments: the client coming back from the provider's page, and the providers' own calls.
		r.Post("/payments/{ref}/confirm", s.payConfirm)
		r.Post("/webhooks/stripe", s.stripeWebhook)
		r.Post("/webhooks/paystack", s.paystackWebhook)

		r.With(s.limit("m-signup", 6, time.Hour)).Post("/m/signup", s.mSignup)
		r.With(s.limit("m-login", 20, 10*time.Minute)).Post("/m/login", s.mLogin)
		r.Post("/m/logout", s.mLogout)
		r.With(s.limit("m-forgot", 6, time.Hour)).Post("/m/forgot", s.mForgot)
		r.With(s.limit("m-reset", 20, time.Hour)).Post("/m/reset", s.mReset)
		r.Route("/m", func(r chi.Router) {
			r.Use(s.requireMerchant)

			// Everyone on the team: the day's work.
			r.Post("/push", s.merchantPush)
			r.Get("/push", s.merchantPush)
			r.Delete("/push", s.merchantPush)
			r.Get("/me", s.mMe)
			r.Post("/customer-profile", s.mCustomer)
			r.Post("/switch", s.mSwitch)
			r.Post("/password", s.mPassword)
			r.Get("/my-day", s.mMyDay)
			r.Get("/calendar-sync", s.mCalSync)
			r.Post("/calendar-sync/feed", s.mCalFeed)
			r.Delete("/calendar-sync/feed", s.mCalFeed)
			r.Put("/calendar-sync/import", s.mCalImport)
			r.Post("/calendar-sync/import/run", s.mCalImportRun)
			r.Get("/security", s.mSecurity)
			r.Post("/2fa/setup", s.m2FASetup)
			r.Post("/2fa/enable", s.m2FAEnable)
			r.Post("/2fa/disable", s.m2FADisable)
			r.Put("/account", s.mAccount)
			r.Post("/account/photo", s.mProfilePhoto)
			r.Delete("/account/photo", s.mProfilePhoto)
			r.Get("/home", s.mHome)
			r.Get("/calendar", s.mCalendar)
			r.Get("/availability", s.mAvailability)
			r.Get("/bookings", s.mBookingSearch)
			r.Post("/bookings", s.mBookingCreate)
			r.Get("/bookings/{id}", s.mBooking)
			r.Post("/bookings/{id}/action", s.mBookingAction)
			r.Post("/blocks", s.mBlockCreate)
			r.Delete("/blocks/{id}", s.mBlockDelete)
			r.Get("/waitlist", s.mWaitlist)
			r.Put("/waitlist/{id}", s.mWaitlistUpdate)
			r.Get("/clients", s.mClients)
			r.Get("/clients/{id}", s.mClient)
			r.Post("/clients", s.mClientCreate)
			r.Put("/clients/{id}", s.mClientUpdate)
			r.Get("/checkout", s.mCheckout)
			r.Post("/checkout", s.mCheckoutPay)
			r.Post("/checkout/link", s.mCheckoutLink)
			r.Post("/checkout/quote", s.mCheckoutQuote)
			r.Get("/payments/{ref}", s.mPayment)
			r.Get("/checkout/day", s.mCheckoutDay)
			r.Get("/inbox", s.mInbox)
			r.Post("/inbox", s.mThreadCreate)
			r.Get("/inbox/{id}", s.mThread)
			r.Post("/inbox/{id}/reply", s.mThreadReply)
			r.Put("/inbox/{id}", s.mThreadUpdate)
			r.Get("/services", s.mServices)
			r.Get("/menu", s.mMenu)
			r.Get("/ai", s.mAI)
			r.Post("/ai/reply", s.mAIReply)
			r.Get("/price-check", s.mPriceCheck)
			r.Get("/clients/{id}/plans", s.mClientPlans)
			r.With(s.mNeedPerm("manager", "see_reports")).Get("/reports", s.mReports)
			r.With(s.mNeedPerm("manager", "see_reports")).Get("/reports/export", s.mReportsExport)
			r.Get("/staff", s.mStaff)
			r.Post("/time-off", s.mTimeOffCreate)

			// Managers and the owner: the menu, the team, stock, marketing and the numbers.
			r.Group(func(r chi.Router) {
				r.Use(s.mNeed("manager"))
				r.Post("/clients/import", s.mClientImport)
				r.Get("/clients/export", s.mClientExport)
				r.Post("/sales/{id}/refund", s.mSaleRefund)
				r.Put("/saved-replies", s.mSavedReplies)
				r.Post("/services", s.mServiceCreate)
				r.Post("/services/import", s.mServiceImport)
				r.Put("/services/{id}/resources", s.mServiceResources)
				r.Post("/resources", s.mResourceSave)
				r.Put("/resources/{id}", s.mResourceSave)
				r.Delete("/resources/{id}", s.mResourceDelete)
				r.Post("/price-rules", s.mPriceRuleSave)
				r.Put("/price-rules/order", s.mPriceRuleOrder)
				r.Put("/price-rules/{id}", s.mPriceRuleSave)
				r.Delete("/price-rules/{id}", s.mPriceRuleDelete)
				r.Post("/packages", s.mPackageSave)
				r.Put("/packages/{id}", s.mPackageSave)
				r.Delete("/packages/{id}", s.mPackageDelete)
				r.Post("/memberships", s.mMembershipSave)
				r.Put("/memberships/{id}", s.mMembershipSave)
				r.Delete("/memberships/{id}", s.mMembershipDelete)
				r.Post("/client-plans/{id}", s.mClientPlanAction)
				r.Post("/rent/{id}", s.mRentAction)
				r.Post("/rent/{id}/link", s.mRentLink)
				r.Post("/products/{id}/photo", s.mProductPhoto)
				r.Delete("/products/{id}/photo", s.mProductPhotoDelete)
				r.Put("/products/{id}/services", s.mProductServices)
				r.Put("/products/{id}/details", s.mProductDetails)
				r.Get("/products/{id}/details", s.mProductDetailsGet)
				r.Get("/intake", s.mIntake)
				r.Post("/intake", s.mIntakeSave)
				r.Put("/intake/{id}", s.mIntakeSave)
				r.Delete("/intake/{id}", s.mIntakeDelete)
				r.Get("/onboarding", s.mOnboarding)
				r.Post("/onboarding/dismiss", s.mOnboardingDismiss)
				r.Post("/verification/documents", s.mVerificationUpload)
				r.Delete("/verification/documents/{id}", s.mVerificationDelete)
				r.Post("/verification/submit", s.mVerificationSubmit)
				r.Get("/returns", s.mReturns)
				r.Post("/returns/{id}", s.mReturnDecide)
				r.Get("/problems", s.mProblems)
				r.Post("/problems/{id}", s.mProblemAnswer)
				r.Get("/shop-policy", s.mShopPolicy)
				r.Put("/shop-policy", s.mShopPolicySave)
				r.Put("/services/order", s.mServiceOrder)
				r.Put("/services/{id}", s.mServiceUpdate)
				r.Post("/services/{id}/action", s.mServiceAction)
				r.Post("/staff", s.mStaffCreate)
				r.Put("/staff/{id}", s.mStaffUpdate)
				r.Post("/staff/{id}/action", s.mStaffAction)
				r.Post("/time-off/{id}", s.mTimeOffDecide)
				r.Get("/payroll", s.mPayroll)
				r.Get("/inventory", s.mInventory)
				r.Get("/orders", s.mOrders)
				r.Post("/orders/{id}", s.mOrderAction)
				r.Post("/products", s.mProductCreate)
				r.Put("/products/{id}", s.mProductUpdate)
				r.Post("/products/{id}/stock", s.mProductStock)
				r.Get("/products/{id}/history", s.mProductHistory)
				r.Post("/suppliers", s.mSupplierCreate)
				r.Delete("/suppliers/{id}", s.mSupplierDelete)
				r.Post("/purchase-orders", s.mPurchaseOrderCreate)
				r.Post("/purchase-orders/{id}", s.mPurchaseOrderAction)
				r.Get("/marketing", s.mMarketing)
				r.Get("/leads", s.mLeads)
				r.Post("/ai/campaign", s.mAICampaign)
				r.Get("/loyalty", s.mLoyalty)
				r.Put("/loyalty/settings", s.mLoyaltySettings)
				r.Post("/loyalty/adjust", s.mLoyaltyAdjust)
				r.Get("/promos", s.mPromos)
				r.Post("/promos", s.mPromoCreate)
				r.Put("/promos/{id}", s.mPromoUpdate)
				r.Delete("/promos/{id}", s.mPromoDelete)
				r.Post("/products/{id}/transfer", s.mProductTransfer)
				r.Post("/storefront/logo", s.mLogoUpload)
				r.Delete("/storefront/logo", s.mLogoDelete)
				r.Put("/automations/{key}", s.mAutomationUpdate)
				r.Post("/campaigns", s.mCampaignCreate)
				r.Delete("/campaigns/{id}", s.mCampaignDelete)
				r.Post("/campaigns/{id}/test", s.mCampaignTest)
				r.Post("/campaigns/{id}/send", s.mCampaignSend)
				r.Get("/storefront", s.mStorefront)
				r.Put("/storefront", s.mStorefrontUpdate)
				r.Post("/storefront/photos", s.mPhotoUpload)
				r.Put("/storefront/photos", s.mPhotoOrder)
				r.Put("/storefront/photos/{id}", s.mPhotoUpdate)
				r.Delete("/storefront/photos/{id}", s.mPhotoDelete)
				r.Post("/reviews/{id}", s.mReviewUpdate)
				r.Get("/settings", s.mSettings)
				r.Put("/settings/profile", s.mSettingsProfile)
				r.Put("/settings/rules", s.mSettingsRules)
				r.Post("/locations", s.mLocationCreate)
				r.Put("/locations/{id}", s.mLocationUpdate)
				r.Post("/locations/{id}/action", s.mLocationAction)
			})

			// The owner only: money, the payout account, the plan, and who can sign in.
			r.Group(func(r chi.Router) {
				r.Use(s.mNeed("owner"))
				r.Get("/money", s.mMoney)
				r.Get("/money/export", s.mMoneyExport)
				r.Get("/statements", s.mStatements)
				r.Get("/payments", s.mPayments)
				r.Get("/statements/{month}", s.mStatement)
				r.Post("/payouts", s.mPayoutNow)
				r.Put("/payout-schedule", s.mPayoutSchedule)
				r.Get("/payout-account", s.mPayoutAccount)
				r.Post("/payout-account/bank", s.mPayoutBank)
				r.Post("/payout-account/stripe", s.mPayoutStripe)
				r.Post("/payout-account/{id}/default", s.mPayoutDefault)
				r.Delete("/payout-account/{id}", s.mPayoutAccountDelete)
				r.Post("/staff/{id}/invite", s.mStaffInvite)
				r.Delete("/staff/{id}/invite", s.mStaffUninvite)
				r.Post("/plan", s.mPlan)
				r.Put("/leads/settings", s.mLeadSettings)
				r.Post("/leads/{id}/dispute", s.mLeadDispute)
				r.Post("/listing", s.mListing)
			})
		})

		r.With(s.limit("a-login", 15, 10*time.Minute)).Post("/admin/login", s.adminLogin)
		r.With(s.limit("a-forgot", 6, time.Hour)).Post("/admin/forgot", s.adminForgot)
		r.With(s.limit("a-reset", 20, time.Hour)).Post("/admin/reset", s.adminReset)

		r.Route("/admin", func(r chi.Router) {
			r.Use(s.requireAdmin)

			// Every role: read the console, handle bookings, leave notes.
			r.Post("/logout", s.adminLogout)
			r.Get("/me", s.adminMe)
			r.Get("/overview", s.adminOverview)
			r.Get("/health", s.adminHealth)
			r.Get("/search", s.adminSearch)
			r.Get("/verification", s.adminVerification)
			r.Get("/moderation", s.adminModeration)
			r.Get("/leads", s.adminLeads)
			r.Get("/disputes", s.adminDisputes)
			r.Get("/businesses", s.adminBusinesses)
			r.Get("/businesses/{id}", s.adminBusiness)
			r.Post("/businesses/{id}/notes", s.adminBusinessNote)
			r.Get("/bookings", s.adminBookings)
			r.Post("/bookings/{id}/action", s.adminBookingAction)
			r.Get("/clients", s.adminClients)
			r.Get("/orders", s.adminOrders)
			r.Get("/products", s.adminProducts)
			r.Get("/payouts", s.adminPayouts)
			r.Get("/fees", s.adminFees)
			r.Get("/flags", s.adminFlags)
			r.Get("/audit", s.adminAudit)
			r.Get("/media", s.adminMedia)
			r.Get("/account", s.adminAccount)
			r.Post("/password", s.adminPassword)
			r.Post("/2fa/setup", s.admin2FASetup)
			r.Post("/2fa/enable", s.admin2FAEnable)
			r.Post("/2fa/disable", s.admin2FADisable)
			r.Get("/promos", s.adminPromos)
			r.Get("/features", s.adminFeatures)
			r.Get("/gift-cards", s.adminGiftCards)
			r.Get("/products/{id}/details", s.adminProductDetailsGet)
			r.Get("/tax-rates", s.adminTaxRates)
			r.Get("/returns", s.adminReturns)
			r.Get("/support", s.adminSupport)
			r.Get("/support/{id}", s.adminSupportTicket)
			r.Post("/support/{id}/reply", s.adminSupportReply)
			r.Put("/support/{id}", s.adminSupportUpdate)
			r.Get("/broadcasts", s.adminBroadcasts)
			r.Get("/pages", s.adminPages)
			r.Get("/journal", s.adminJournal)
			r.Get("/journal/{id}", s.adminJournalOne)

			// Ops: decisions that move money or change what the public sees.
			r.Group(func(r chi.Router) {
				r.Use(s.need("ops"))
				// Identity documents: the papers themselves, not the queue. Support sees the queue and the decision.
				r.Get("/verification/{id}/documents", s.adminVerificationDocs)
				r.Get("/verification-documents/{id}", s.adminVerificationDoc)
				r.Get("/attention", s.adminAttention)
				r.Post("/verification/{id}/decide", s.adminVerificationDecide)
				r.Post("/moderation/{id}/decide", s.adminModerationDecide)
				r.Post("/disputes/{id}/resolve", s.adminDisputeResolve)
				r.Post("/leads/{id}/resolve", s.adminLeadResolve)
				r.Post("/businesses/{id}/status", s.adminBusinessStatus)
				r.Patch("/businesses/{id}", s.adminBusinessUpdate)
				r.Post("/businesses/{id}/review-summary", s.adminReviewSummary)
				r.Post("/businesses/{id}/payout-hold", s.adminPayoutHold)
				r.Post("/businesses/{id}/credits", s.adminCredit)
				r.Post("/clients/block", s.adminClientBlock)
				r.Post("/orders/{id}/status", s.adminOrderStatus)
				r.Post("/products/{id}/active", s.adminProductActive)
				r.Post("/payouts/{id}/action", s.adminPayoutAction)
				r.Post("/media", s.adminMediaUpload)
				r.Get("/export/{kind}", s.adminExport)
				r.Post("/businesses", s.adminBusinessCreate)
				r.Put("/businesses/{id}/profile", s.adminBusinessProfile)
				r.Put("/locations/{id}", s.adminLocationUpdate)
				r.Post("/businesses/{id}/services", s.adminServiceCreate)
				r.Put("/services/{id}", s.adminServiceUpdate)
				r.Delete("/services/{id}", s.adminServiceDelete)
				r.Post("/businesses/{id}/staff", s.adminStaffCreate)
				r.Put("/staff/{id}", s.adminStaffUpdate)
				r.Delete("/staff/{id}", s.adminStaffDelete)
				r.Post("/products", s.adminProductCreate)
				r.Put("/products/{id}", s.adminProductUpdate)
				r.Put("/products/{id}/details", s.adminProductDetails)
				r.Post("/promos", s.adminPromoCreate)
				r.Put("/promos/{id}", s.adminPromoUpdate)
				r.Delete("/promos/{id}", s.adminPromoDelete)
				r.Post("/gift-cards", s.adminGiftCardIssue)
				r.Post("/gift-cards/{id}/void", s.adminGiftCardVoid)
				r.Post("/broadcasts", s.adminBroadcastCreate)
				r.Delete("/broadcasts/{id}", s.adminBroadcastDelete)
				r.Put("/media/{id}", s.adminMediaUpdate)
				r.Delete("/media/{id}", s.adminMediaDelete)
				// The Journal: writing and taking down. Publishing is the super admin's, below.
				r.Post("/journal", s.adminJournalCreate)
				r.Post("/journal/draft", s.adminJournalDraft)
				r.Put("/journal/{id}", s.adminJournalUpdate)
				r.Post("/journal/{id}/unpublish", s.adminJournalUnpublish)
				r.Post("/journal/{id}/archive", s.adminJournalArchive)
				r.Delete("/journal/{id}", s.adminJournalDelete)
			})

			// Super admin: pricing, rollouts, and who has access.
			r.Group(func(r chi.Router) {
				r.Use(s.need("super_admin"))
				r.Post("/fees", s.adminFeesPropose)
				r.Put("/features/{key}", s.adminFeatureSet)
				r.Post("/fees/decide", s.adminFeesDecide)
				r.Put("/leads/rates", s.adminLeadRate)
				r.Post("/flags", s.adminFlagCreate)
				r.Put("/flags/{key}", s.adminFlagUpdate)
				r.Delete("/flags/{key}", s.adminFlagDelete)
				r.Get("/team", s.adminTeam)
				r.Post("/team", s.adminTeamCreate)
				r.Put("/team/{id}", s.adminTeamUpdate)
				r.Post("/team/{id}/reset-2fa", s.adminTeamReset2FA)
				r.Post("/merchants/reset-2fa", s.adminMerchantReset2FA)
				r.Put("/tax-rates/{region}", s.adminTaxRateSet)
				r.Delete("/tax-rates/{region}", s.adminTaxRateSet)
				r.Post("/returns/{id}", s.adminReturnDecide)
				r.Post("/attention/refunds/{id}/retry", s.adminRefundRetry)
				r.Get("/settings/referral", s.adminReferral)
				r.Put("/settings/referral", s.adminReferralSave)
				r.Post("/broadcasts/{id}/send", s.adminBroadcastSend)
				r.Put("/pages/{slug}", s.adminPageUpdate)
				r.Post("/journal/{id}/publish", s.adminJournalPublish)
			})
		})
	})
	return r
}

func (s *Server) cors(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")
		for _, o := range s.cfg.CORSOrigins {
			if o == origin || o == "*" {
				w.Header().Set("Access-Control-Allow-Origin", origin)
				w.Header().Set("Vary", "Origin")
				w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
				w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
				w.Header().Set("Access-Control-Expose-Headers", "Content-Disposition")
				break
			}
		}
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

func logRequests(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)
		next.ServeHTTP(ww, r)
		slog.Info("http", "method", r.Method, "path", r.URL.Path, "status", ww.Status(), "ms", time.Since(start).Milliseconds())
	})
}

// actor is the signed-in admin's email, written to the audit log.
func (s *Server) actor(r *http.Request) string {
	if a := currentAdmin(r); a.Email != "" {
		return a.Email
	}
	return "unknown"
}
