begin transaction read only;
select json_build_object(
 'paid_deposits_without_ledger',coalesce((select json_agg(x) from (select p.id,p.reference,p.amount_cents,p.currency,p.booking_id,b.status from payments p join bookings b on b.id=p.booking_id where p.purpose='deposit' and p.status='paid' and p.refunded_cents<p.amount_cents and b.status not like 'cancelled%' and not exists(select 1 from ledger l where l.booking_id=p.booking_id and l.kind='deposit'))x),'[]'),
 'paid_sales_without_sale',coalesce((select json_agg(x) from (select p.id,p.reference,p.amount_cents,p.currency from payments p where p.purpose='sale' and p.status='paid' and not exists(select 1 from sales s where s.id=p.sale_id))x),'[]'),
 'paid_orders_without_ledger',coalesce((select json_agg(x) from (select p.id,p.reference,p.order_id,p.amount_cents,p.currency from payments p where p.purpose='order' and p.status='paid' and not exists(select 1 from ledger l where l.order_id=p.order_id and l.kind='charge') and exists(select 1 from order_shipments sh where sh.order_id=p.order_id and sh.items_cents>0))x),'[]'),
 'duplicate_deposit_ledger',coalesce((select json_agg(x) from (select booking_id,count(*) rows,sum(amount_cents) amount_cents from ledger where kind='deposit' and booking_id is not null group by booking_id having count(*)>1)x),'[]'),
 'paid_bookings_without_sale',coalesce((select json_agg(x) from (select b.id,b.business_id,b.total_cents,biz.currency,b.paid_at from bookings b join businesses biz on biz.id=b.business_id where b.status='paid' and not exists(select 1 from sales s where s.booking_id=b.id))x),'[]'),
 'invalid_refund_totals',coalesce((select json_agg(x) from (select id,reference,amount_cents,refunded_cents from payments where refunded_cents<0 or refunded_cents>amount_cents)x),'[]'),
 'refund_intents_pending',coalesce((select json_agg(x) from (select id,payment_id,amount_cents,status,problem from payment_refunds where status in ('created','sending','unknown'))x),'[]'),
 'cancelled_paid_deposits_needing_review',coalesce((select json_agg(x) from (select p.id,p.reference,p.booking_id,p.amount_cents,p.refunded_cents,b.status from payments p join bookings b on b.id=p.booking_id where p.purpose='deposit' and p.status='paid' and b.status like 'cancelled%' and p.refunded_cents<p.amount_cents and not exists(select 1 from payment_refund_jobs j where j.payment_id=p.id))x),'[]'),
 'sale_charge_mismatches',coalesce((select json_agg(x) from (select s.id,s.business_id,s.total_cents,s.tip_cents,(select sum(l.amount_cents) from ledger l where l.sale_id=s.id and l.kind in ('charge','tip')) ledger_cents from sales s where exists(select 1 from ledger l where l.sale_id=s.id and l.kind='charge') and s.total_cents <> (select coalesce(sum(l.amount_cents),0) from ledger l where l.sale_id=s.id and l.kind in ('charge','tip')))x),'[]')
);
commit;
